# Site settings
port: 4000
title: JRubyArt (Code as Art)
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  JRubyArt is a ruby wrapper for processing-3.1.1+ For processing-2.2.1, use
  ruby-processing.
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
urls:
  bugs: https://github.com/ruby-processing/JRubyArt/issues
  wiki: https://github.com/ruby-processing/JRubyArt/wiki
  github: https://ruby-processing.github.io/JRubyArt
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true
  css: syntax.css        
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
